feat: 認証にCookieを使うように、ページロードにloaderを使うように
pulsate-dev/caramel pull request #22
Opened 2024-10-17 14:55 UTC by laminne

close #21 
## やったこと
- 認証にcookieを使うように
  - セキュリティー周りの調整はほぼしていません
- ロードにloader(remixの機能)を使うように
  - サーバーサイドでAPIアクセスが完結するように
  - 同時にタイムライン取得のフックをlibに移動させました

2024-10-17 15:29 UTC, MikuroXina requested changes

2024-10-17 15:29 UTC, MikuroXina commented on app/lib/login.ts
> +    return (await response.json()) as { authorization_token: string };
このコードを強制的なキャストに変更しているようですが, (今後の仕様変更などで) レスポンスの形式が期待するものでなくなった場合に実行時エラーも起こらず気づきにくくなると思います. 変更しないままにするか, 明示的なバリデーションを追加したほうがよいかと思います.

2024-10-17 15:29 UTC, MikuroXina commented on app/lib/timeline.ts
> +      signal: abortController.signal,
```suggestion
  try {
    const timelineRes = await fetch("http://localhost:3000/timeline/home", {
      headers: {
        authorization: `Bearer ${token}`,
      },
```
この `AbortController` はどこからも使用されていないので効果がないと思います.
もし停止できるようにしたいのであれば, この関数の引数として外部から `AbortController` を受け取るようにすることで, この関数を呼び出す側から停止できるようにするでしょう. しかしこれはフロントエンドサーバーからバックエンドサーバーへのリクエストであるため, クライアントから停止を制御できません. 実施する意味が無いと思います.

2024-10-17 15:29 UTC, MikuroXina commented on app/routes/timeline.tsx
> +  const notes = useLoaderData<typeof loader>();
`notes` または `error` が格納されたオブジェクトが入る変数名を `notes` とするのは混乱を招きそうです. 素直に `loaderData` などはどうでしょうか.

2024-10-18 02:03 UTC, m1sk9 approved these changes

2024-10-18 02:47 UTC, MikuroXina approved these changes

2024-10-18 04:15 UTC, merged